### ISSUE TITLE
Error de validacion del correo del usuario alumnodaw2@iesdosmares.com

### ISSUE THREAD

**Issue by ghost** [2DAW-2Mares/viajeEstudios#24]
Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials

La posible solución la explican aquí : 
https://stackoverflow.com/questions/31516821/node-js-email-doesnt-get-sent-with-gmail-smtp

Parece que hay que conceder permisos a apps externas a google.
Saludos.

**Comment by albsierra** [comment]
Buscar siempre primero en la documentación oficial.

También te indica [aquí](http://loopback.io/doc/en/lb3/Email-connector.html#using-gmail) la solución:
Using GMail

> Tip: With GMail, you may need to enable the “access for less secure apps” option. See:
> 
>     Nodemailer: Using GMail
>     Nodemailer: Authentication for more information.
