### ISSUE TITLE
warning: possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by ghost** [2DAW-2Mares/viajeEstudios#27]
Al ejecutar AUTOMIGRATE=true node .  la consola devuelve el siguiente aviso:

(node) warning: possible EventEmitter memory leak detected. 12 connected listeners added. Use emitter.setMaxListeners() to increase limit.

La aplicación continúa con la ejecución. Alternativamente, la solución la he encontado agregando la siguiente línea:
require('events').EventEmitter.prototype._maxListeners = 15;
 al inicio del fichero /server/server.js.

Fuente: https://stackoverflow.com/questions/8313628/node-js-request-how-to-emitter-setmaxlisteners

**Comment by albsierra** [comment]
Solucionado con el pull request #30 de @AlDev1
